### ISSUE TITLE
Infix

### ISSUE THREAD

**Issue by soegaard** [BourgondAries/k-infix#1]
Hi. 

Nice package. You mention in the readme that the infix package is unhygienic
due to using strings. This sounds odd. Infix was written to work with the
macro system, so it should have a nice behavior. 

If you have an example that demonstrates otherwise, it is a bug. 
(If so please file a bug report). 

/Jens Axel

**Comment by BourgondAries** [comment]
That was my first impression. I'll remove that part until I find an example of broken hygiene. Thank you.

**Comment by soegaard** [comment]
No problem.
